# Generated by Django 5.0 on 2023-12-27 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="theatrehall",
            options={"ordering": ["-id"], "verbose_name_plural": "theatre_halls"},
        ),
    ]
