# Generated by Django 5.0 on 2023-12-28 19:31

import theatre.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theatre", "0004_alter_performance_play_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theatre.models.actor_image_file_path
            ),
        ),
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theatre.models.play_image_file_path
            ),
        ),
    ]
